### ISSUE TITLE
Enable use of the Docker provider in Vagrant for testing local servers

### ISSUE THREAD

**Issue by mikemccllstr** [CoderDojoTC/python-minecraft#6]
The solo-server configuration should be replaced with a top-level Vagrant file that uses the Docker provider to host our image (e.g., "coderdojotc/python-minecraft-student" on the Docker Hub).

This will enable students and developers to stand up an environment in much less time, with much less data downloaded, and with fewer moving parts.

**Comment by raypitmon** [comment]
Very nice!

When I tried to stand up a new solo instance, I quickly found out that I didn't have docker installed. (Which lead me down the path of a complete reinstall of Ubuntu, since I was running an ancient Lucid!  :)

So, you may want to update the install steps to include installing docker:  https://docs.docker.com/installation/#installation

After getting everything installed, it started up just fine.  Also - I'm guessing that I really didn't need virtualbox since the change to docker and the fact that I'm using Linux.

It would also be nice to have a few hints on how to connect to the minecraft server console in this new environment (I'm trying to figure that out right now).
